---
title: "covariance portfolio Notebook"
output: html_notebook
---


```{r}
library(rugarch)
library(xdcclarge)
library(RiskPortfolios)
library(rmgarch)
library(Matrix)
library('matrixcalc')
library('RcppCNPy')
```


# test speed

```{r}
n = 10
days = 100
test_data = read.csv('./test_500_1260.csv')
Rtn = test_data[1:days, 2:(n+1)]
t1 = Sys.time()
cov_pred = dcc_cov_pre(Rtn, n)
t2 = Sys.time()
print(t2-t1)
```




# loading data
```{r}
data = read.csv("./df_rolls.csv", sep=",")
df_rolls <- as.matrix(data)
```


```{r}
data_630 = read.csv("./df_rolls_500_630.csv", sep=",")
df_rolls_630 <- as.matrix(data_630)
```


# 1/N sample and covariance portfolio
```{r}

res_portfolio <- function(res_pre, ws){
  res <- res_pre%*%ws
  return(res)
}

ew_portfolio <- function(df_rolls, N, days, month_days, num_trade){
  res_all = c()
  for(i in c(1:num_trade)){
    st_sam  = (i-1) * (days + month_days) + 1
    ed_sam = st_sam + days - 1
    st_pre = ed_sam + 1
    ed_pre = st_pre + month_days - 1
    res_pre = df_rolls[st_pre:ed_pre, 2:(N+1)]
    ews = matrix(rep(1/N, times=N))
    res_i = res_pre %*% ews
    res_all <- c(res_all, res_i)}
  return(res_all)}

samcov_portfolio <- function(df_rolls, N, days, month_days, num_trade){
  res_all = c()
  for(i in c(1:num_trade)){
    st_sam  = (i-1) * (days + month_days) + 1
    ed_sam = st_sam + days - 1
    st_pre = ed_sam + 1
    ed_pre = st_pre + month_days - 1
    res_sam = df_rolls[st_sam:ed_sam, 2:(N+1)]
    res_pre = df_rolls[st_pre:ed_pre, 2:(N+1)]
    sam_cov = cov(res_sam)
    if(is.positive.definite(sam_cov, tol=1e-8)==FALSE){
      cov_temp = nearPD(sam_cov, ensureSymmetry=FALSE)
      sam_cov = matrix(cov_temp$mat)
    }
    ws = optimalPortfolio(Sigma=sam_cov, 
         control=list(type='minvol'))
    ws = matrix(ws)
    res_i = res_pre %*% ws
    res_all <- c(res_all, res_i)
  }
  return(res_all)
}

indicators <- function(all_res){
  AV = round(mean(all_res)*252*100, 4)
  SD = round(cov(all_res, all_res)**0.5*252**0.5*100, 4)
  IR = round(AV/SD, 4)
  return(c(AV, SD, IR))
}
```

```{r}
# computing the returns
num_trade = 190
all_res_ew = ew_portfolio(df_rolls, 500, 1260, 21, num_trade)
indicators(all_res_ew)
#all_res_sam_100 = samcov_portfolio(df_rolls, 100, 1260, 21, num_trade)


result_ew = indicators(all_res_ew)
result_sa = indicators(all_sam_ew)
table <- (rbind(result_ew, result_sa))
colnames(table) <- c('AV','SD','IR')
rownames(table) <- c('equal weights','sample covariance')
table
```





# NL-DCC portfoilio

```{r}
dcc_cov_pre <- function(Rtn, N){
# Step 1:GARCH Parameter Estimation with rugarch
spec = ugarchspec(variance.model=list(
model = "sGARCH", garchOrder = c(1, 1), submodel = NULL, 
external.regressors = NULL, variance.targeting = FALSE), 
mean.model = list(armaOrder = c(1, 1), 
include.mean = TRUE, archm = FALSE, 
archpow = 1, arfima = FALSE, 
external.regressors = NULL, archex = FALSE), 
distribution.model = "norm", 
start.pars = list(), fixed.pars = list())

mspec = multispec(replicate(spec, n=N))
fitlist = multifit(multispec=mspec, solver="hybrid",
          data = Rtn) 
ht<-sigma(fitlist)^2 
residuals<-residuals(fitlist)

forecasts = multiforecast(fitlist, data = NULL, n.ahead = 21, n.roll = 0,
out.sample = 0, external.forecasts = list(mregfor = NULL, vregfor = NULL),
cluster = NULL)
vars = sigma(forecasts)
# Step 2:DCC-GARCH Parameter Estimation with xdcclarge
#DCC<-dcc_estimation(ini.para=c(0.05,0.93) , ht, residuals) 
#Time varying correlation matrix Rt at time t 
#Rt<-matrix(DCC$dcc_Rt, n, n)
cDCC <- cdcc_estimation(ini.para=c(0.01,0.50),
        ht, residuals,method='NLS', ts=21)
cov_all = 0 
for(i in c(1:21)){
  corr_i = matrix(cDCC$cdcc_Rt[i, ], N, N)
  var_i = diag(vars[i, 1, ])
  cov_i = var_i%*%corr_i%*%var_i
  
  cov_all <- cov_all + cov_i
}
cov_all = cov_all/21 
return(cov_all)
}


dccnl_portfolio <- function(df_rolls, N, days, month_days, num_trade, root_dir){
  res_all = c()
  for(i in c(1:num_trade)){
    print(i)
    t1 = Sys.time()
    st_sam  = (i-1) * (days + month_days) + 1
    ed_sam = st_sam + days - 1
    st_pre = ed_sam + 1
    ed_pre = st_pre + month_days - 1
    print(c(st_sam, ed_sam, st_pre, ed_pre))
    res_sam = df_rolls[st_sam:ed_sam, 2:(N+1)]
    res_pre = df_rolls[st_pre:ed_pre, 2:(N+1)]
    cov_pred = dcc_cov_pre(res_sam, N)
    file_path = paste(root_dir, i, '.csv', sep='')
    write.table(cov_pred,  file=file_path, row.names = TRUE, col.names =TRUE, sep=',')
    ws = optimalPortfolio(Sigma=cov_pred, 
         control=list(type='minvol'))
    ws = matrix(ws)
    res_i = res_pre %*% ws
    res_all <- c(res_all, res_i)
    t2 = Sys.time()
    print(t2-t1)
  }
  return(res_all)
}
```


```{r}
cov_pred = dcc_cov_pre(res_sam, N)
```



```{r}
all_res_dccnl = dccnl_portfolio(df_rolls, 100, 1260, 21)
```


```{r}
num_trade = 190
root_dir = '~/Desktop/courses_term3/Master_project/data/cov_200_dcc1/'
all_res_dccnl_1260_200 = dccnl_portfolio(df_rolls, 200, 1260, 21, num_trade, root_dir)
```

```{r}
dccnl_portfolio1 <- function(df_rolls, N, days, month_days, num_trade, root_dir){
  res_all = c()
  for(i in c(1:num_trade)){
    t1 = Sys.time()
    print(i)
    st_sam  = (i-1) * (days + month_days) + 1
    ed_sam = st_sam + days - 1
    st_pre = ed_sam + 1
    ed_pre = st_pre + month_days - 1
    print(c(st_sam, ed_sam, st_pre, ed_pre))
    res_sam = df_rolls[st_sam:ed_sam, 2:(N+1)]
    res_pre = df_rolls[st_pre:ed_pre, 2:(N+1)]
    file_path = paste(root_dir, i, '.csv', sep='')
    cov_pred = read.csv(file_path)
    cov_pred = matrix(as.matrix(cov_pred), N, N)
    ws = optimalPortfolio(Sigma=cov_pred, 
         control=list(type='minvol'))
    ws = matrix(ws)
    res_i = res_pre %*% ws
    res_all <- c(res_all, res_i)
    t2 = Sys.time()
    print(t2-t1)
  }
  return(res_all)
}
```

```{r}
all_res_dccnl_1260_500 = dccnl_portfolio1(df_rolls, 500, 1260, 21, num_trade, root_dir)
```




```{r}

cov_ff_pre<-function(Rtns, N, n_head=21){
# multi-univarite Garch specification:
spec = ugarchspec(variance.model=list(
model = "sGARCH", garchOrder = c(1, 1), submodel = NULL, 
external.regressors = NULL, variance.targeting = FALSE), 
mean.model = list(armaOrder = c(1, 1), 
include.mean = TRUE, archm = FALSE, 
archpow = 1, arfima = FALSE, 
external.regressors = NULL, archex = FALSE), 
distribution.model = "norm", 
start.pars = list(), 
fixed.pars = list())
mspec = multispec(replicate(spec, n=N))

# fit multi-univariate  garch
fitlist = multifit(multispec=mspec, solver="hybrid",
          data = Rtns) 
ht<-sigma(fitlist)^2 
residuals<-residuals(fitlist)

# prediction diag element of variance.
forecasts = multiforecast(fitlist, data = NULL, n.ahead = 21, n.roll = 0,
out.sample = 0, external.forecasts = list(mregfor = NULL, vregfor = NULL),
cluster = NULL)
vars = sigma(forecasts)


# fit dcc-garch
cDCC <- cdcc_estimation(ini.para=c(0.01,0.50),
        ht, residuals, method='COV', ts=21)

# predict average forcast covariance matrix
cov_all = 0 
for(i in c(1:n_head)){
  corr_i = matrix(cDCC$cdcc_Rt[i, ], N, N)
  var_i = diag(vars[i, 1, ])
  cov_i = var_i%*%corr_i%*%var_i
  
  cov_all <- cov_all + cov_i
}
cov_avg = cov_all/n_head
return(cov_avg)
}

get_cov_ls<-function(ffdata){
    st_id = 6348
    sam_size = 1260
    j = 0
    ff_ls = c('Mkt.RF', 'SMB', 'HML', 'RMW', 'CMA')
    while(st_id + sam_size + 21 <= 11602){
        print(j)
        t1 = Sys.time()
        trading_i = st_id + sam_size
        ffdata_i =ffdata[ff_ls][1:trading_i, ]
        cov_ff_i = cov_ff_pre(ffdata_i, 5, 21)
        if(j == 0){cov_ff_all = cov_ff_i}
        else{cov_ff_all<- rbind(cov_ff_all, cov_ff_i)}
        st_id <- st_id + 21
        j <- j + 1
        t2 = Sys.time()
        print(t2-t1)
    }
return(cov_ff_all)}
```


# predict the covariance matrix of five factors.
```{r}
file_path = '~/Desktop/courses_term3/Master_project/data/ffdata_11062.csv'
ffdata = read.csv(file_path)
ff_ls = c('Mkt.RF', 'SMB', 'HML', 'RMW', 'CMA')
cov_ff_all = get_cov_ls(ffdata)
```





# predict residual dcc-nl covariance matrix
```{r}
dccnl_resid_cov_pre <- function(resid_matrix, N, num_trade, root_dir){
  res_all = c()
  for(i in c(1:num_trade)){
    print(i)
    t1 = Sys.time()
    st_sam  = (i-1) * 500 + 1
    ed_sam = st_sam + N - 1
    resid_sam = t(resid_matrix[st_sam:ed_sam, ])
    print(c(st_sam, ed_sam))
    cov_pred = dcc_cov_pre(resid_sam, N)
    file_path = paste(root_dir, i, '.csv', sep='')
    write.table(cov_pred,  file=file_path, row.names = TRUE, col.names =TRUE, sep=',')
    t2 = Sys.time()
    print(t2-t1)
  }}
```


```{r}
N = 100
num_trade = 190
resid5_matrix = npyLoad("./Desktop/courses_term3/Master_project/data/ff_model_data/residual_mat5.npy")
root_dir = './Desktop/courses_term3/Master_project/data/ff_model_data/resid_dcc_cov5_100/'
dccnl_resid_cov_pre(resid5_matrix, N, num_trade, root_dir)
```

